services:
  nightgames-frontend:
    container_name: nightgames-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${NIGHTGAMES_PORT:-8088}:80"
    restart: unless-stopped